/** Generated by scripts/fetch-bili-avatars.js. */
export const BILI_AVATAR_MAPPING: Record<string, string> = {
  '7552204': 'https://i1.hdslb.com/bfs/face/40a3cce5ce83edf18ef0d144772fd3d94d6b3d3f.jpg',
  '19642758': 'https://i0.hdslb.com/bfs/face/a163d177a378ac99d070c569bef34fe18c08b057.jpg',
  '13354765': 'https://i1.hdslb.com/bfs/face/6787192a42ca29aa5f496b8fc471c898ad4c6378.jpg',
  '147166910': 'https://i2.hdslb.com/bfs/face/4267567b355286e2004d76eedcdafed6da317192.jpg',
  '416128940': 'https://i2.hdslb.com/bfs/face/a618cc74513b8d8c5b4d4b72406ddceeaab96aa2.jpg',
  '474702359': 'https://i2.hdslb.com/bfs/face/34d9a63447f9a24a3cb6929c72e0f68a776b4427.jpg',
  '16539048': 'https://i0.hdslb.com/bfs/face/1c514726c0afd56e2e463ad4f25174cb877a8f9b.jpg',
  '1526101': 'https://i1.hdslb.com/bfs/face/d4dfe0bb19af9ffa0e060de7af61dec4393bd192.jpg',
  '257975429': 'https://i2.hdslb.com/bfs/face/cd7c38ada477f81e7b256cc23bf616bbcab7e409.jpg',
  '8366990': 'https://i2.hdslb.com/bfs/face/60368b5e2850cc569328e8b562d90cb28ce5b2cd.jpg',
  '116683': 'https://i1.hdslb.com/bfs/face/8fad84a4470f3d894d8f0dc95555ab8f2cb10a83.jpg',
  '21876627': 'https://i0.hdslb.com/bfs/face/7197ba7d67ca73cdf63214bd02916063045dfb23.jpg',
  '33416285': 'https://i2.hdslb.com/bfs/face/059d712c25e6d2571c736e0470b7e43222fa7cb3.jpg',
  '4229234': 'https://i2.hdslb.com/bfs/face/3e41053a12843294e86d5b17c2c79474402dbf5c.jpg',
  '306895558': 'https://i1.hdslb.com/bfs/face/93a7371c185067d166126322cf768702d7c049d9.jpg',
  '18202105': 'https://i1.hdslb.com/bfs/face/54b5c9c2ad7f1baff195090bfd6afa365ef20c37.jpg',
  '18343098': 'https://i0.hdslb.com/bfs/face/d90c454f699e8ce3043a75c39c7473d12ffe07f5.jpg',
  '130636947': 'https://i0.hdslb.com/bfs/face/b23b68a60d4330aaa04c7785594bacad3837ff11.jpg',
  '194484313': 'https://i1.hdslb.com/bfs/face/84a861facfa041b46f7a30897e9ed3f2e05e0519.jpg',
  '848008': 'https://i1.hdslb.com/bfs/baselabs/31800ff06f145d3a42378a036ca4695dd60233c8.png',
  '632887': 'https://i1.hdslb.com/bfs/face/38d85946c9cd0cf159e4d646be63fad36c2486c1.jpg',
  '11870568': 'https://i0.hdslb.com/bfs/face/047b747ba0f47353b312a89b4216a04f035ad316.jpg',
  '41642624': 'https://i2.hdslb.com/bfs/face/0d39243c39eb9ab1eb7f5b307eccfaac956bf2d4.jpg',
  '900171': 'https://i0.hdslb.com/bfs/face/c5e5d9be42ba2fdaecd8eddcff6cfe728350752d.jpg',
  '696795220': 'https://i1.hdslb.com/bfs/face/373a616a087ddb0e959732e93a1b04a1a87caae6.jpg',
  '15385187': 'https://i2.hdslb.com/bfs/face/e37d01c3ea133d932a71299d4f86fa8d5fdf29ae.jpg',
  '642922': 'https://i1.hdslb.com/bfs/face/ecafa05a88ad0cfb4444706282324d80a8b39606.jpg',
  '210752': 'https://i2.hdslb.com/bfs/face/8e5c3a6acf4a48df121963815141e7be9d9f329b.jpg',
  '1600113': 'https://i0.hdslb.com/bfs/face/a5814e1ae9b9f5a6e3e8c012a0d2b344f8fec1cf.gif',
  '18841842': 'https://i0.hdslb.com/bfs/baselabs/9c42c7e10f1da635678a47dbce4f92f04c45496f.png',
};

export function getBiliOfficialAvatar(uid?: string): string | null {
  return uid ? BILI_AVATAR_MAPPING[uid]?.replace(/^http:/, 'https:') || null : null;
}
