
import { Game } from '../types';

export const GAMES_CONFIG: Game[] = [
  {
    id: "b-001",
    season: 1,
    levelName: "配对游戏",
    rule: "两人互相选择, 未被选中的人淘汰。",
    levelChampion: "",
    levelEliminated: "力元君",
    url: "https://www.bilibili.com/video/BV1CQ4y1f7dA?t=547.2"
  },
  {
    id: "b-002",
    season: 1,
    levelName: "加法游戏",
    rule: "每位选手持有一套数字牌（1～5）, 轮流打牌, 累加已出的牌面数字。累加等于 %10% 即获胜；超过 %10% 则“爆炸”, 本轮所出的牌全部作废并没收, 从零重新开始。",
    levelChampion: "",
    levelEliminated: "自来卷三木, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1Hq4y1Q7r2?t=727.5"
  },
  {
    id: "b-003",
    season: 1,
    levelName: "奥运会",
    rule: "选手需依次完成五项运动项目：第一项%跨栏%, 第二项%投球%, 第三项%桌球%, 第四项%乒乓球%, 第五项%游泳%。两组分别参赛计时, 累计用时更短的一组获胜。",
    levelChampion: "",
    levelEliminated: "在下哲别, 啊吗粽",
    url: "https://www.bilibili.com/video/BV1Y64y1s7X8?t=332.4"
  },
  {
    id: "b-004",
    season: 1,
    levelName: "捉迷藏",
    rule: "一人找、一人藏。每人有%三次%寻找机会, 每次限时%10分钟%：找到得1分, 未找到不得分, %累计得分高者%获胜。",
    levelChampion: "力元君, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1Rf4y1V7tC?t=333.7"
  },
  {
    id: "g-001",
    season: 2,
    levelName: "夹纸牌",
    rule: "用%头顶%接住从墙面落下的纸牌, 队伍中有一人夹住即过关。",
    levelChampion: "力元君, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "徐大虾咯, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=214.2"
  },
  {
    id: "g-002",
    season: 2,
    levelName: "3个6",
    rule: "投掷骰子, %掷出三个6%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=301.3"
  },
  {
    id: "g-003",
    season: 2,
    levelName: "吹气球",
    rule: "吹爆%5个气球%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=434.8"
  },
  {
    id: "g-004",
    season: 2,
    levelName: "爱莲说",
    rule: "背诵指定文言文《%爱莲说%》, %一字不落%即过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 雨哥到处跑",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=552.9"
  },
  {
    id: "g-005",
    season: 2,
    levelName: "拔河",
    rule: "三组轮流%拔河%对决, %输的一方罚时半小时%。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 雨哥到处跑",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=815.3"
  },
  {
    id: "g-006",
    season: 2,
    levelName: "投乒乓",
    rule: "将乒乓球%投进玻璃杯%即过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "力元君, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=1120.8"
  },
  {
    id: "g-007",
    season: 2,
    levelName: "扔飞镖",
    rule: "两人轮流投掷, 共用%6支飞镖%, 累计命中%红心2次%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "力元君, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=1315.3"
  },
  {
    id: "g-008",
    season: 2,
    levelName: "呼啦圈",
    rule: "用%脖子%转呼啦圈, %连续10个不断%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "力元君, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=1502.3"
  },
  {
    id: "g-009",
    season: 2,
    levelName: "数10s",
    rule: "心中默数%10秒%, 与裁判计时器同时开始；误差在%±0.1秒%内（9.9s～10.1s）即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "力元君, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=1544.9"
  },
  {
    id: "g-010",
    season: 2,
    levelName: "十连投",
    rule: "投篮连续命中%10个%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=1644.4"
  },
  {
    id: "g-011",
    season: 2,
    levelName: "十连颠",
    rule: "用乒乓球拍%握柄%颠球, %连续颠15下%即过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 雨哥到处跑",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eL4y1z7ZY?t=2131.4"
  },
  {
    id: "g-012",
    season: 2,
    levelName: "踢毽子",
    rule: "两人相互踢毽子, 完成%5个来回%（共%10次%）即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    giveUp: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=292.0"
  },
  {
    id: "g-013",
    season: 2,
    levelName: "套圈儿",
    rule: "一人于%指定位置%站立不动, 另一人用呼啦圈抛套, %套中%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=511.2"
  },
  {
    id: "g-014",
    season: 2,
    levelName: "猜扑克",
    rule: "先选定一张目标牌（如%红桃10%）, 再从扑克牌中抽牌；未抽中则%洗牌%重抽, %抽中%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=557.4"
  },
  {
    id: "g-015",
    season: 2,
    levelName: "桌球",
    rule: "须按%视频演示%的进球方式完成进球即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=1018.1"
  },
  {
    id: "g-016",
    season: 2,
    levelName: "唱童话",
    rule: "演唱%《童话》%, 评分达到%3S%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=1158.2"
  },
  {
    id: "g-017",
    season: 2,
    levelName: "钓鱼",
    rule: "两人合作钓鱼, %钓到一条%即过关。",
    levelChampion: "无",
    giveUp: "徐大虾咯, 雨哥到处跑, 力元君, 自来卷三木, 啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=1407.1"
  },
  {
    id: "g-018",
    season: 2,
    levelName: "纸飞机",
    rule: "折一架纸飞机, %穿过小窗口%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=1794.0"
  },
  {
    id: "g-019",
    season: 2,
    levelName: "扔水瓶",
    rule: "扔水瓶使其落地, %连续5次%即过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "力元君, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1yq4y1V7vh?t=1875.4"
  },
  {
    id: "g-020",
    season: 2,
    levelName: "十连猜",
    rule: "猜手中骰子在左手还是右手, %连续猜对10次%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "力元君, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    giveUp: "力元君, 自来卷三木, 啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=153.3"
  },
  {
    id: "g-021",
    season: 2,
    levelName: "叠五层",
    rule: "将纸牌叠至%五层%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    giveUp: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=381.8"
  },
  {
    id: "g-022",
    season: 2,
    levelName: "转到你",
    rule: "裁判转动桌面指针, 选手可自由放置纸片；旋转结束时, %指针落在纸片范围内%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=983.4"
  },
  {
    id: "g-023",
    season: 2,
    levelName: "碰撞球",
    rule: "两人相距%3米%, 分别抛掷乒乓球, %在空中相撞%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=1142.0"
  },
  {
    id: "g-024",
    season: 2,
    levelName: "找东西",
    rule: "在场地内寻找裁判藏好的物品, %三样物品中找到任意一件%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=1266.4"
  },
  {
    id: "g-025",
    season: 2,
    levelName: "你画我猜",
    rule: "一人作画一人猜；作画者仅可绘画, 不得说话、做肢体动作或写字；%猜中%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=1419.1"
  },
  {
    id: "g-026",
    season: 2,
    levelName: "猜点数",
    rule: "两人各持骰盅（内含%3枚骰子%）, 每轮摇盅后各自猜点数之和；%两人均猜中%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1jh411n7f8?t=1651.6"
  },
  {
    id: "g-027",
    season: 2,
    levelName: "擦边球",
    rule: "用白球击打%圈内%的黑球, 使黑球上的硬币%弹飞出圈%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=237.3"
  },
  {
    id: "g-028",
    season: 2,
    levelName: "高空投篮",
    rule: "从%二楼%将足球投至%一楼%的篮球框, %投进一球%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=521.1"
  },
  {
    id: "g-029",
    season: 2,
    levelName: "掷壶",
    rule: "将笔投向%正前方%的水瓶, 笔须在%空中旋转180°%后%落入瓶内%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=746.1"
  },
  {
    id: "g-030",
    season: 2,
    levelName: "打水漂",
    rule: "打水漂, %一次连续打出5个%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=841.6"
  },
  {
    id: "g-031",
    season: 2,
    levelName: "吹杯子",
    rule: "吹气使杯子滑入%对面%的杯内, %套中3次%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    giveUp: "徐大虾咯, 雨哥到处跑, 在下哲别, 啊吗粽",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=985.2"
  },
  {
    id: "g-032",
    season: 2,
    levelName: "连连看",
    rule: "将%26张牌%随机排列于桌面, 按%A到K%的顺序依次翻出同点数的两张（先两张A, 再两张2……直至两张K）, %全部翻对%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=1712.1"
  },
  {
    id: "g-033",
    season: 2,
    levelName: "夹骰子",
    rule: "将骰子抛向空中, 用%筷子%在落地前%夹住%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=1786.1"
  },
  {
    id: "g-034",
    season: 2,
    levelName: "停在这",
    rule: "从%桌面一端%投出乒乓球, 使球停在%两条线之间%的区域内即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    levelRunnerUp: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=1864.4"
  },
  {
    id: "g-035",
    season: 2,
    levelName: "砸水瓶",
    rule: "用手掷出足球, 将%远处%的%10个装满水的瓶子%全部%击倒%即过关。",
    levelChampion: "徐大虾咯, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1AT4y1d7bC?t=1954.9"
  },
  {
    id: "g-036",
    season: 3,
    levelName: "翻牌",
    rule: "%6张卡牌%通过手掌扇风的方式, %一次性全部%翻面即可通过。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=220.4"
  },
  {
    id: "g-037",
    season: 3,
    levelName: "寻找海洋球",
    rule: "在海洋球里找到1个%印有标记%的海洋球即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=275.2"
  },
  {
    id: "g-038",
    season: 3,
    levelName: "切香蕉",
    rule: "利用%飞牌%把香蕉%切断或插上%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    giveUp: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=315.1"
  },
  {
    id: "g-039",
    season: 3,
    levelName: "情歌对唱",
    rule: "两人一起演唱一首歌曲, 最终评分为%SSS%即过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    giveUp: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=492.2"
  },
  {
    id: "g-040",
    season: 3,
    levelName: "杯中乒乓",
    rule: "乒乓球扔上高空原地旋转%360度%, 用杯子接住累计%3次%球。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=803.1"
  },
  {
    id: "g-041",
    season: 3,
    levelName: "打字测试",
    rule: "测试%1分钟内%打拼音, 两人平均速率值超过%350个%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    giveUp: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=992.1"
  },
  {
    id: "g-042",
    season: 3,
    levelName: "羽毛球进洞",
    rule: "把羽毛球%打进桶里%打进%2个%即可过关",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=1261.2"
  },
  {
    id: "g-043",
    season: 3,
    levelName: "蒙眼花圆",
    rule: "%蒙上眼睛%在基准圆的外圆画一个首尾相接的圆, 误差不超过%2毫米%。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QT4y1e79k?t=1513.6"
  },
  {
    id: "g-044",
    season: 3,
    levelName: "骰子王",
    rule: "放%十个以内%的骰子, 摇出%三个叠在一起%的即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=228.2"
  },
  {
    id: "g-045",
    season: 3,
    levelName: "半米罗汉",
    rule: "找%十个以上%的石头叠起来, 高度%超过半米%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=342.5"
  },
  {
    id: "g-046",
    season: 3,
    levelName: "国足旺旺",
    rule: "把球%踢中洞口%, %砸中板凳%即可过关。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=596.9"
  },
  {
    id: "g-047",
    season: 3,
    levelName: "双人投壶",
    rule: "双人以%击地%的方式, 同时把乒乓球%投进杯子里%即可过关, 杯子里可以加水。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    giveUp: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=718.1"
  },
  {
    id: "g-048",
    season: 3,
    levelName: "四色球",
    rule: "两人同时把手伸进海洋球里, 同时拿出%四个颜色相同%的球即可过关。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=873.5"
  },
  {
    id: "g-049",
    season: 3,
    levelName: "雀神",
    rule: "同时%猜对%手里摸的麻将即可过关。",
    levelChampion: "徐大虾咯, 自来卷三木",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=1018.9"
  },
  {
    id: "g-050",
    season: 3,
    levelName: "弹弓Biu",
    rule: "做一个%弹弓%, 用%乒乓球%把羽毛球飞掉。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1mY4y1H7wp?t=1261.6"
  },
  {
    id: "g-051",
    season: 3,
    levelName: "造船术",
    rule: "用任意材料造出一艘%“船”%, 在游泳池上接力划%一个来回%即可过关。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    giveUp: "啊吗粽, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=599.3"
  },
  {
    id: "g-052",
    season: 3,
    levelName: "1杆3洞",
    rule: "一杆进洞%三个球%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    giveUp: "力元君, 在下哲别, 徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=1144.2"
  },
  {
    id: "g-053",
    season: 3,
    levelName: "拿捏",
    rule: "别墅内随意拿一件物体称重, 必须超过%一百克以上%, 猜的误差不能超过%1克%。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=1473.6"
  },
  {
    id: "g-054",
    season: 3,
    levelName: "背数字",
    rule: "每组随便写20个数字, 一共%60个数字%要全部%默写%出来。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=1515.7"
  },
  {
    id: "g-055",
    season: 3,
    levelName: "你画我猜",
    rule: "一方画画, 一方猜字, 互相猜出其他组写的%四字词语%即可过关。",
    levelChampion: "徐大虾咯, 自来卷三木",
    levelRunnerUp: "啊吗粽, 雨哥到处跑",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=1707.1"
  },
  {
    id: "g-056",
    season: 3,
    levelName: "跳大绳",
    rule: "两人合作一起跳绳, 跳%三十个%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=2061.4"
  },
  {
    id: "g-057",
    season: 3,
    levelName: "小圈套",
    rule: "像套圈一样, 把%橡皮筋%完整套到%羽毛球%上即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1XZ4y1y7du?t=2213.6"
  },
  {
    id: "g-058",
    season: 3,
    levelName: "小孔成像",
    rule: "通过圆锥直筒里的小洞, 找到阿姨丢在草坪里的%三颗玻璃球%, 每组找到%一颗%即为过关。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "啊吗粽, 雨哥到处跑",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    giveUp: "力元君, 在下哲别, 啊吗粽, 雨哥到处跑, 徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=632.7"
  },
  {
    id: "g-059",
    season: 3,
    levelName: "贴玻璃",
    rule: "用透明胶把人贴在玻璃上%双脚离地%, 坚持%20秒%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=948.2"
  },
  {
    id: "g-060",
    season: 3,
    levelName: "抓动物",
    rule: "抓%一只%野生动物带到别墅里, 动物体型%大于1cm%即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑, 徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=1225.3"
  },
  {
    id: "g-061",
    season: 3,
    levelName: "穿针引线",
    rule: "一分钟之内将线穿进%五根针%中, 即为过关, 需由一人独立完成。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=1475.5"
  },
  {
    id: "g-062",
    season: 3,
    levelName: "骰子沙漏",
    rule: "将%6颗骰子%以%沙漏(⏳)的形状%, 叠两组即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=1632.9"
  },
  {
    id: "g-063",
    season: 3,
    levelName: "乒乓杯",
    rule: "一方发球, 一方接球。接球方将球%打进%桌子中间的红酒杯中, 即可过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=1827.1"
  },
  {
    id: "g-064",
    season: 3,
    levelName: "吹乒乓",
    rule: "两个人站在柱子台面两边吹乒乓球, 让乒乓球在柱子中间%保持平衡不要掉落%, 从一端吹到另一端撞到另一端的墙面, 即为成功。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=1956.6"
  },
  {
    id: "g-065",
    season: 3,
    levelName: "瓶壶",
    rule: "两个人站在桌子两端, 桌子两端桌面上分别画有%两个圆圈%, 从一端推出水瓶使%正好停在圆圈中%即为过关(一个人通过即可)。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1eY411P7kW?t=2180.1"
  },
  {
    id: "g-066",
    season: 3,
    levelName: "捡垃圾",
    rule: "出门捡%两个%可回收的塑料瓶, 易拉罐或牛奶盒一类的可以装液体的容器, 即可过关(%不可以在垃圾桶翻找%)",
    levelChampion: "徐大虾咯, 自来卷三木",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "啊吗粽, 雨哥到处跑",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=213.7"
  },
  {
    id: "g-067",
    season: 3,
    levelName: "黄力元投篮",
    rule: "%一共6个球%, 2白, 2黄, 2红。%白球1分, 黄球2分, 红球3分%。%桶最近的×1, 中间×2, 最远的×3%。例如：红球投中最远的为：3×3=9分, 投到自己满意为止, 在白板上记录分数。如果有后面队来把前面人的记录破掉之后, 前面的人还需要回来, 继续持平或者打破这个记录(前面的关卡冻结)。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "啊吗粽, 雨哥到处跑",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=346.0",
    isSpecialLevel: true,
    specialLevelType: 'ball',
    specialBestScore: '24分'
  },
  {
    id: "g-068",
    season: 3,
    levelName: "牙签！冲！",
    rule: "每队插进%三根牙签%立在纸板上, 即为过关",
    levelChampion: "徐大虾咯, 自来卷三木",
    levelRunnerUp: "啊吗粽, 雨哥到处跑",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=572.2"
  },
  {
    id: "g-069",
    season: 3,
    levelName: "扫雷",
    rule: "%中级%难度挑战成功, 即为过关",
    levelChampion: "徐大虾咯, 自来卷三木",
    levelRunnerUp: "啊吗粽, 雨哥到处跑",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=678.6"
  },
  {
    id: "g-070",
    season: 3,
    levelName: "蒙眼投篮",
    rule: "%蒙住%眼睛听队友%指挥%进%一球%, 即可过关",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "徐大虾咯, 自来卷三木",
    levelThirdPlace: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=959.4"
  },
  {
    id: "g-071",
    season: 3,
    levelName: "石子戏法",
    rule: "抛起一个石子, 在石子落下前抓起%桌子上的1颗石子%再接住落下的石子。%再抛起一颗石子%, 落下前抓起%桌子上的2颗石子%, 再接住落下的石子。%再抛起%, 再抓起%桌上的3颗石子%, 再接住落下的石子。都接住之后将石子全部抛起手背接住, 再用手背将石子%全部抛起%再接住落下的全部石子, 即为过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    giveUp: "啊吗粽, 雨哥到处跑, 力元君, 在下哲别, 徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=1031.1"
  },
  {
    id: "g-072",
    season: 3,
    levelName: "量尺寸",
    rule: "从别墅里找到一个物体带回桌面上测量, 得到测量数字与报出的预计数字误差不超过%0.2cm%, 即为过关",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1HF411T7oV?t=1840.5"
  },
  {
    id: "g-073",
    season: 3,
    levelName: "回旋飞机",
    rule: "飞机扔出去, 双脚站在%原地不动%, 飞机飞回来再%抓住%, 合计通过两次即为通关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=392.8"
  },
  {
    id: "g-074",
    season: 3,
    levelName: "Show Time",
    rule: "用%报纸%做一件%上衣%, 穿在身上完成今天剩下的所有游戏。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    levelThirdPlace: "徐大虾咯, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=580.5"
  },
  {
    id: "g-075",
    season: 3,
    levelName: "钻木取火",
    rule: "利用道具把%火%点起来",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=960.3"
  },
  {
    id: "g-076",
    season: 3,
    levelName: "羽毛球接力",
    rule: "一方%发球%, 另一方%接球%。接球方接到球后将球打入%蓝色桶%内即为过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=1169.7"
  },  
  {
    id: "g-077",
    season: 3,
    levelName: "打玻璃珠",
    rule: "站在四格地砖后, 用手里的玻璃球%击中%五角星拖上的%玻璃珠%, 即为过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=1286.8"
  },
  {
    id: "g-078",
    season: 3,
    levelName: "飞牌穿缝",
    rule: "桌子上垒起一排书, 用%扑克牌%飞出%穿过%书中间留下的%缝隙%, 即为过关。",
    levelChampion: "啊吗粽, 雨哥到处跑",
    levelRunnerUp: "力元君, 在下哲别",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=1382.9"
  },
  {
    id: "g-079",
    season: 3,
    levelName: "啦转圈",
    rule: "持续转%一分钟%即为成功。",
    levelChampion: "力元君, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 啊吗粽",
    giveUp: "雨哥到处跑, 啊吗粽",
    url: "https://www.bilibili.com/video/BV1AT4y167mt?t=1528.1"
  },
  {
    id: "g-080",
    season: 4,
    levelName: "110分贝",
    rule: "需要两个人合作%超过110分贝%才能通过(如果声音到不了110分贝, 借助外力达到也是可以的)。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV128411G7by?t=171.7"
  },
  {
    id: "g-081",
    season: 4,
    levelName: "气球入洞",
    rule: "将吹好的%气球%, 通过%放气%的形式, 让它进入瓶中（办法随意）。",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=345.9"
  },
  {
    id: "g-082",
    season: 4,
    levelName: "射击游戏",
    rule: "FPS准星两个队友加起来超过%12W%, 即可过关(可以一直刷新自己的战绩, 双方以最高分相加超过12w即可)。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=663.3"
  },
  {
    id: "g-083",
    season: 4,
    levelName: "情感大考验",
    rule: "每组成员两两一起划船到湖心岛, 选择某一位成员的%异性家属或伴侣%拨通电话, 5秒内对面未接通电话视为挑战失败, 需要重新从对面划船到湖心岛(一人挑战成功即可过关)。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=1035.6"
  },
  {
    id: "g-084",
    season: 4,
    levelName: "枕头大作战",
    rule: "两人%背对背%互相%扔枕头%, 眼睛不能看枕头, %同时接住%, 即可过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=1458.7"
  },
  {
    id: "g-085",
    season: 4,
    levelName: "书写田字格",
    rule: "按照顺序书写%1-300%数字, 书写规范, 不能涂改, 不能写错, 否则挑战失败, 重头开始。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=1800.1"
  },
  {
    id: "g-086",
    season: 4,
    levelName: "宅舞大考验",
    rule: "每组根据%《触摸天空》%四句歌词, 和队友编排一个%宅舞%。四句歌词按照到达此关卡的名次顺延, (正义女神可以参与指导)。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=1973.8"
  },
  {
    id: "g-087",
    season: 4,
    levelName: "蒙眼走弯路",
    rule: "蒙着眼睛走完全程, %双手不可以触摸任何物体%来进行定位, 行走过程中%碰到墙壁即为挑战失败%。每队有一人成功即可过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV128411G7by?t=2469.4"
  },
  {
    id: "g-088",
    season: 4,
    levelName: "乒乓球",
    rule: "把%乒乓球%丢入金属%木桶%不弹出, 每组两人都需要投进一个, 即可过关。",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=482.6"
  },
  {
    id: "g-089",
    season: 4,
    levelName: "世界线收束",
    rule: "%正义女神指定b站一个视频%, 每组成员退出b站账号后, 通过点击视频相关推荐, 一直点到女神指定的视频。（%一人成功即可通过%）",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=630.0"
  },
  {
    id: "g-090",
    season: 4,
    levelName: "抓蜻蜓",
    rule: "每组去户外非常温柔的%抓住一只蜻蜓%, 可以利用各种道具方式, 抓到后%成功放生%。即可过关。",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=885.0"
  },
  {
    id: "g-091",
    season: 4,
    levelName: "吸管大接力",
    rule: "每组通过拼接吸管, 由一人站在远处, %把矿泉水喝完%即为过关。（%二人可以接力%）",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=1061.9"
  },
  {
    id: "g-092",
    season: 4,
    levelName: "射箭",
    rule: "两个人都%射中十环%即可过关",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    giveUp: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=1452.4"
  },
  {
    id: "g-093",
    season: 4,
    levelName: "沙滩足球",
    rule: "%蒙着眼睛%运球或者踢球, 把球%踢进球门%即可过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "力元君, 徐大虾咯",
    giveUp: "力元君, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=1706.2"
  },
  {
    id: "g-094",
    season: 4,
    levelName: "弹力乒乓球",
    rule: "每组队员在桌面上乒乓球来回弹, 触碰桌面序列逐渐增加%从1到7%, 即可过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "力元君, 徐大虾咯",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=2133.2"
  },
  {
    id: "g-095",
    season: 4,
    levelName: "躲避水瓶",
    rule: "蒙眼躲避水瓶%10次%, 不被水瓶碰到即可通过, 一人成功即可。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "力元君, 徐大虾咯",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=2244.2"
  },
  {
    id: "g-096",
    season: 4,
    levelName: "猜价格",
    rule: "根据女神选择的照片, 猜价格, 精确到个位数即可过关。",
    levelChampion: "力元君, 徐大虾咯",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1gG4y1g7f7?t=2358.5"
  },
  {
    id: "g-097",
    season: 4,
    levelName: "爆炸吧气球",
    rule: "气球%抛过头顶%, 然后用自己折的纸飞机%扎破气球%即可过关。(一人通过即可)",
    levelChampion: "力元君, 徐大虾咯",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1mK411i7xh?t=226.6"
  },
  {
    id: "g-098",
    season: 4,
    levelName: "燃烧我的卡路里",
    rule: "两个人加在一起共计消耗%600卡路里%, 即可过关。",
    levelChampion: "力元君, 徐大虾咯",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    giveUp: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1mK411i7xh?t=351.2"
  },
  {
    id: "g-099",
    season: 4,
    levelName: "挑战高尔夫",
    rule: "%一杆进洞%, 现场任意一条球道都可以使用, 两个人都需要%一杆进洞%才可过关。",
    levelChampion: "力元君, 徐大虾咯",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1mK411i7xh?t=1083.0"
  },
  {
    id: "g-100",
    season: 4,
    levelName: "篮球不会说谎",
    rule: "背对篮筐, 投进%三分球%, 两个人都需要投进才可过关。",
    levelChampion: "力元君, 徐大虾咯",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1mK411i7xh?t=1497.2"
  },
  {
    id: "g-101",
    season: 4,
    levelName: "M豆大作战",
    rule: "%M豆堆叠4颗%即可过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 徐大虾咯",
    giveUp: "力元君, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1mK411i7xh?t=1710.5"
  },
  {
    id: "g-102",
    season: 4,
    levelName: "想不到吧",
    rule: "正义女神在别墅里藏了一句话, 共%10个字%, 分散在别墅各个角落, 需要通过找字, %猜测出女神的原话%是什么。",
    levelChampion: "",
    url: "https://www.bilibili.com/video/BV1mK411i7xh?t=1848.9"
  },
  {
    id: "g-103",
    season: 4,
    levelName: "飞牌截胡",
    rule: "10张牌同时丢到空中, 两个人同时抓到%大小王%即可过关",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=226.7"
  },
  {
    id: "g-104",
    season: 4,
    levelName: "便利贴男孩",
    rule: "每个人身上贴%20张便利贴%, 通过身体的抖动把便利贴%甩干净%, (%需要两人一起完成%)即可过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=374.0"
  },
  {
    id: "g-105",
    season: 4,
    levelName: "x是谁？",
    rule: "裁判定一个人名, 队员%每分钟只能问裁判一个问题%, 裁判只能回答%(是/否)%准确猜测出裁判定的人名即可通过。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=730.5"
  },
  {
    id: "g-106",
    season: 4,
    levelName: "咸咸的甜",
    rule: "60杯水中有%3杯糖水%, 从中挑选一杯, 组员随机%喝到糖水%即可过关。必须%喝光手中的水%才能选择下一杯继续。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "力元君, 徐大虾咯",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=1142.8"
  },
  {
    id: "g-107",
    season: 4,
    levelName: "唱歌识曲",
    rule: "学一首%除英语之外的外语歌%, 用软件%听歌识曲%识别出来, 即可过关。第一组通关唱歌识曲的队伍拥有歌曲选择的权利, 后面两组要用%第一组通关歌曲%去通关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "力元君, 徐大虾咯",
    levelThirdPlace: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=1376.1"
  },
  {
    id: "g-108",
    season: 4,
    levelName: "许愿池",
    rule: "站在圈外把%硬币丢到雕塑上%, 让它%停留在上面%。一人过关即可。",
    levelChampion: "",
    giveUp: "雨哥到处跑, 自来卷三木, 徐大虾咯, 力元君, 啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=1965.6"
  },
  {
    id: "g-109",
    season: 4,
    levelName: "逗女神笑",
    rule: "想方设法让女神%笑出来%, 即可过关。",
    levelChampion: "",
    url: "https://www.bilibili.com/video/BV1NG4y1j78a?t=2105.4"
  },
  {
    id: "g-110",
    season: 4,
    levelName: "你帅吗？",
    rule: "正义女神根据6个up主的颜值进行%前三名排序%, 每个人都需要%猜对自己的名次%, 后三名直接说后三名即可。猜对即可过关, 猜错原地等待%5分钟%进行下一关。(两人都猜错需等待10分钟)",
    levelChampion: "",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=220.4"
  },
  {
    id: "g-111",
    season: 4,
    levelName: "朋友的问候",
    rule: "所有人手机摆在台面上, 手机收到%消息通知亮起%, 即可通关。(每组一人过关即可)",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 力元君",
    giveUp: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=375.0"
  },
  {
    id: "g-112",
    season: 4,
    levelName: "女神的天秤",
    rule: "女神在天秤的一侧摆一件物品, 每组成员需要在别墅内找到一件%同等质量%的物件摆在天秤另一侧, 使天秤处于%完全平衡状态%。可以通过%调节天秤时刻砝码%使天秤保持平衡。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=574.5"
  },
  {
    id: "g-113",
    season: 4,
    levelName: "羽毛球穿洞",
    rule: "所有人在%一米开外%, 把羽毛球%打进行动的洞洞中%即可过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=772.6"
  },
  {
    id: "g-114",
    season: 4,
    levelName: "杯杯叠叠乐",
    rule: "叠三层被纸牌隔离的杯子, %抽掉中间两张纸牌%后, 杯子掉落后%叠在一起%即可过关。(一人过关即可)",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=955.3"
  },
  {
    id: "g-115",
    season: 4,
    levelName: "你多大啦",
    rule: "每组成员随机找路人猜年龄, 两个人的年龄都被%猜到了%即可过关。每个路人只有%一次机会%哦~",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=1030.6"
  },
  {
    id: "g-116",
    season: 4,
    levelName: "省份猜猜猜",
    rule: "正义女神随机在地图上找一个城市和县城, 队员根据市县的名字%猜测出这个城市的省份%, %猜对即可过关%哦。猜错%罚时一分钟%继续。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=1490.1"
  },
  {
    id: "g-117",
    season: 4,
    levelName: "走位大比拼",
    rule: "玩走位游戏, 每组队员%生存时间的平均值%高于%女神的赛绩%即可过关。",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    giveUp: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=1850.1"
  },
  {
    id: "g-118",
    season: 4,
    levelName: "旋转球拍",
    rule: "用%单个手指%旋转羽毛球拍%50圈%即可过关。(一人过关即可)",
    levelChampion: "徐大虾咯, 力元君",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=2402.1"
  },
  {
    id: "g-119",
    season: 4,
    levelName: "夹住乒乓球",
    rule: "每组成员拿筷子%一个丢球, 一个接球%, %接住一个乒乓球%即可过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "啊吗粽, 在下哲别",
    giveUp: "啊吗粽, 在下哲别",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=2583.9"
  },
  {
    id: "g-120",
    season: 4,
    levelName: "羽毛球颠颠颠",
    rule: "每组成员拿羽毛板%颠乒乓球%来回%15个不落地%即可过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 在下哲别",
    levelThirdPlace: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1WG4y1C7mT?t=2728.6"
  }, 
  {
    id: "sp-001",
    season: 4,
    levelName: "隔空进球",
    spTag: "准度",
    rule: "拿乒乓球先%弹一下第一张桌子%, 然后再%弹进第二张桌子的水杯中%。(一人过关即可。)",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1TT41117DK?t=301.4"
  },
  {
    id: "sp-002",
    season: 4,
    levelName: "如影随形",
    spTag: "默契",
    rule: "裁判说%一个词%, 两个人需要做出%相同的动作%即可过关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1TT41117DK?t=649.4"
  },
  {
    id: "sp-003",
    season: 4,
    levelName: "黄力元投币",
    spTag: "运气",
    rule: "每个队都可以连续投掷硬币的某一面%直到自己满意的成绩%, 如果后面的人过来把前面的人记录超越了, 前面的人还要回来把记录%持平或者超越%。(持平的话别的组可以不用回来继续闯关, 否则就要%无限循环%！)",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1TT41117DK?t=971.9",
    isSpecialLevel: true,
    specialLevelType: 'coin',
    specialBestScore: '10连'
  },
  {
    id: "sp-004",
    season: 4,
    levelName: "高空抛水瓶",
    spTag: "技巧",
    rule: "水瓶%从低处往高处丢%, %立在上面%即可过关。%一人通过即可%。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1TT41117DK?t=1108.0"
  },
  {
    id: "sp-005",
    season: 4,
    levelName: "记忆扑克牌",
    spTag: "智力",
    rule: "每组队员需要记忆一副扑克牌的%顺序和花色%。队员间牌数可以自由分配, %54张牌全部背诵正确%后, 即可通关。",
    levelChampion: "啊吗粽, 在下哲别",
    levelRunnerUp: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1TT41117DK?t=1902.4"
  },
  {
    id: "sp-006",
    season: 4,
    levelName: "终极游戏",
    spTag: "力量",
    rule: "通过%踢球%的方式, %正面击中%桩子本体。使桩子掉落到地面即可成为%通关王%！",
    levelChampion: "徐大虾咯, 力元君",
    url: "https://www.bilibili.com/video/BV1TT41117DK?t=2623.2"
  },
  {
    id: "g-121",
    season: 5,
    levelName: "兵乓球吃吃吃",
    rule: "双方互相朝对方丢乒乓球, 直到%两人同时吃到对方丢过来的乒乓球%方为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=303.9"
  },
  {
    id: "g-122",
    season: 5,
    levelName: "名梗猜猜猜",
    rule: "由女神告诉其中一人一句话, 该人%不能说话只能靠肢体语言%比划, 另一个人%完整猜出句子%则为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=373.4"
  },
  {
    id: "g-123",
    season: 5,
    levelName: "圈圈圆圆套套",
    rule: "两人使用塑料圈%同时套中%两个%远近不同的桩子%则为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=550.2"
  },
  {
    id: "g-124",
    season: 5,
    levelName: "乒乓摇摇摇",
    rule: "两人身后绑上装满%25颗乒乓球%的盒子, 在手%不能碰到盒子和乒乓球%的情况下, 使两人乒乓球%全部掉落%则为过关(队友可以互相帮助)。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=799.3"
  },
  {
    id: "g-125",
    season: 5,
    levelName: "弹弓射射射",
    rule: "两人使用弹弓%同时击倒%远处%两个瓶子%则为过关。",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    giveUp: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=997.7"
  },
  {
    id: "g-126",
    season: 5,
    levelName: "谁是流量密码",
    rule: "两人开启直播, 直播人数达到%3000人%即为过关。(%不需要同时%)",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    giveUp: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=1536.9"
  },
  {
    id: "g-127",
    season: 5,
    levelName: "饮料配配配",
    rule: "由女神打乱下方饮料, 其中一位玩家只能提示上下两组饮料中%对了几个%, 另一个玩家通过提示挪动上方饮料, 直到与下方饮料%顺序一致%则为过关。",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=1995.0"
  },
  {
    id: "g-128",
    season: 5,
    levelName: "台球粒子碰撞",
    rule: "两位玩家互相朝对方滚台球, 台球必须要在%碰撞之后%%滚入洞里%才算过关。(注：台球起始点必须在%桌子两边的中间部位%)",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1QfgNzCEcm?t=2209.8"
  },
  {
    id: "g-129",
    season: 5,
    levelName: "足球上下楼",
    rule: "两人一组打好充气足球后, 手不碰球把球运到三楼, 并在三楼%叼住一个乒乓球%后下楼。全程%手不能碰到足球和墙%。(如果碰到就要%重一楼重新开始%)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=181.5"
  },
  {
    id: "g-130",
    season: 5,
    levelName: "大地艺术",
    rule: "一名队友在%一楼%用这个房子里的物品, %摆出形状%让楼上的队友猜。%猜对%就过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=430.8"
  },
  {
    id: "g-131",
    season: 5,
    levelName: "绝对同步",
    rule: "一名队友负责扔盆, 另一名负责丢水瓶, 盆%停止移动%的同时, 瓶子要正好%立在盆上%。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=530.8"
  },
  {
    id: "g-132",
    season: 5,
    levelName: "舌尖美味",
    rule: "裁判将三种不同的饮料混合成一杯果汁, 需要正确说出裁判用的%哪三种饮料%。%答错一次罚时五分钟%。(为了避免颜色信息, 饮料用老抽调色)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=657.0"
  },
  {
    id: "g-133",
    season: 5,
    levelName: "数字建筑",
    rule: "每人从1-10的扑克牌中抽一张数字, 并在%卫星地图上%找到对应数字的建筑。%两人都找到%就算过关。建筑由裁判负责审核是否通过。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=1008.1"
  },
  {
    id: "g-134",
    season: 5,
    levelName: "足球踢踢踢",
    rule: "两人轮流踢球, %从数字1提到数字9%, %必须两人轮流踢%",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    giveUp: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=1241.0"
  },
  {
    id: "g-135",
    season: 5,
    levelName: "杯子三门问题",
    rule: "三个杯子中有一个硬币, 第一次选好一个杯子后, 裁判会%去除一个错误答案%, 需要从剩下的两个杯子中%重新选择正确答案%。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=1650.6"
  },
  {
    id: "g-136",
    season: 5,
    levelName: "硬币抓抓抓",
    rule: "在手背上摆好三枚硬币, 将硬币抛起后, 在硬币%落地前分三次抓住%。(必须是%分开三次%, 姿势为抓, 其他姿势都不算)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=1770.1"
  },
  {
    id: "g-137",
    season: 5,
    levelName: "人名猜猜猜",
    rule: "各组需要通过问问题猜出自己组的对应人名是什么, 裁判只能回答%是和不是%。(谜底人名大家都认识)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=2094.9"
  },
  {
    id: "g-138",
    season: 5,
    levelName: "球球拍拍拍",
    rule: "两人需要以%指定的姿势%进行抛球, 两人同时抛球并且两人要%同时接住%对方丢来的球。",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1D2bUzjEoo?t=2693.1"
  },
  {
    id: "g-139",
    season: 5,
    levelName: "舌尖上的火龙果",
    rule: "由其中一位玩家背起另一位玩家, 背上的玩家需要在%不能肢体接触到火龙果%的情况下%吃完火龙果%则为过关。(吃没吃完由女神决定)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=158.6"
  },
  {
    id: "g-140",
    season: 5,
    levelName: "女神的声波测试",
    rule: "女神站在%距离两位玩家10m以外%的地方, 通过%发出声音%让玩家%猜与女神之间的距离%。(每次回答后会有女神的远近提示)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=488.3"
  },
  {
    id: "g-141",
    season: 5,
    levelName: "安静一会儿",
    rule: "女神从%指定的书中%指出一个词, 玩家%找到一样的词%即为过关。(不同位置也可)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=755.3"
  },
  {
    id: "g-142",
    season: 5,
    levelName: "跳跃的乒乓球",
    rule: "两位玩家需要%同时把乒乓球%从装满水的杯子吹到%另一个杯子里%, 直到%第十个杯子%即为过关。(吹一次只能前进一个杯子)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=958.3"
  },
  {
    id: "g-143",
    season: 5,
    levelName: "充电宝弹弹弹",
    rule: "只需猜出4个充电宝中, 哪一个%会弹出来%即为过关。猜错则需%冷却5分钟%再继续, 猜错的充电宝%不能归还%, 下一个到达该关卡的玩家直接%继承上一队充电宝进度%。(如果上一队过关则充电宝重置)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=1193.9"
  },
  {
    id: "g-144",
    season: 5,
    levelName: "吸铁石吸吸吸",
    rule: "玩家只需%使用吸铁石%从%户外%吸到重达的%1000克铁%则为%过关%。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    giveUp: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=1554.6"
  },
  {
    id: "g-145",
    season: 5,
    levelName: "计算器加加加",
    rule: "两人%轮流%使用计算器%在10秒内%把女神出的%10个数字%相加并且%答案正确%即为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    giveUp: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=2252.8"
  },
  {
    id: "g-146",
    season: 5,
    levelName: "穿梭的乒乓球",
    rule: "两人%互相打%同一个乒乓球, 直到%来回穿过%面前三个洞口并最后%接住%则视为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=2503.3"
  },
  {
    id: "g-147",
    season: 5,
    levelName: "不断错过的足球",
    rule: "两人互相朝对方踢足球, 直到%同时%踢入对方身后的%球框%则为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=2554.5"
  },
  {
    id: "g-148",
    season: 5,
    levelName: "泳池寻宝",
    rule: "只要两人从泳池里的%3000个海洋球%中, 找出%球体内有色子的海洋球%即可。",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1Je8mz8EX6?t=2749.9"
  },
  {
    id: "g-149",
    season: 5,
    levelName: "蒙眼敲锣",
    rule: "玩家需要站在%指定的位置%, %蒙眼%使用%沙包投掷%, 使%远处的锣发出声音%则为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=289.3"
  },
  {
    id: "g-150",
    season: 5,
    levelName: "究极地狱恐怖投壶",
    rule: "两位玩家需要站在%台阶上%, %朝下方壶内投入木棍%则为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=388.3"
  },
  {
    id: "g-151",
    season: 5,
    levelName: "麻将你拼我猜",
    rule: "一位玩家%想出一个词语%并且使用麻将拼出图案, 另一位%通过图案猜出词语%即为过关。(%落后的队伍需要猜前一对的词%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=462.8"
  },
  {
    id: "g-152",
    season: 5,
    levelName: "一笔画人",
    rule: "两位玩家%分别画出一个人物%, 只要%女神猜出其中一位%则为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=635.4"
  },
  {
    id: "g-153",
    season: 5,
    levelName: "小学生问答",
    rule: "女神通过卡片%向玩家提出问题%, 两位玩家%轮流答题%且%不能沟通%, 直到两位玩家连续答对%6道题%则为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=752.4"
  },
  {
    id: "g-154",
    season: 5,
    levelName: "打车猜颜色",
    rule: "玩家需要在%起点%打一辆车, 然后需要%猜出这辆车是什么颜色%, 猜对%坐车到达终点再回来%就算过关, 猜错则需要%再终点再猜一次%, 来回直到%猜中为止%。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=1178.2"
  },
  {
    id: "g-155",
    season: 5,
    levelName: "麻将你拼我猜2.0",
    rule: "与%1.0规则%一样但是要%猜其他队的词%",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=1668.2"
  },
  {
    id: "g-156",
    season: 5,
    levelName: "乐器挑战",
    rule: "使用%拇指琴%弹奏%周杰伦%, 女神通过玩家%弹奏的音乐%猜中是哪一首歌就算过关。(%周杰伦的歌需要随机%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=1948.5"
  },
  {
    id: "g-157",
    season: 5,
    levelName: "乒乓弹力占位",
    rule: "两位玩家需要在%指定位置%, 使乒乓球在桌面弹一次后%落入面前红酒杯中三次%就算过关。(%每个杯内有且只能有只一颗乒乓球%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=2621.8"
  },
  {
    id: "g-158",
    season: 5,
    levelName: "一滴眼泪",
    rule: "任意一位玩家只需要能%留下一滴眼泪%即为过关。(%必须肉眼可见%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=2793.9"
  },
  {
    id: "g-159",
    season: 5,
    levelName: "飞盘丢桶",
    rule: "两位玩家需要站在%水池边的指定位置%, 并把手中的飞盘飞入%水池对面的蓝色桶内%即为过关。(%不需要同时%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV18CtBz1E6t?t=3041.3"
  },
  {
    id: "g-160",
    season: 5,
    levelName: "抽便利贴",
    rule: "同一组人需要从另一名队友身上%抽便利贴%, 同组人一共%抽下十张%就算过关。(%必须使用指定工具%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=134.5"
  },
  {
    id: "g-161",
    season: 5,
    levelName: "锤丸",
    rule: "两位玩家需要使用%特定工具%, 将小球打入%对面球洞%。每人进%一颗球%, 即为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=432.6"
  },
  {
    id: "g-162",
    season: 5,
    levelName: "人格测试",
    rule: "需要猜对女神的%MBTI人格%, 每%三分钟%可以问女神一个问题。%答对%就过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=687.9"
  },
  {
    id: "g-163",
    season: 5,
    levelName: "智力锁",
    rule: "两人一共要解开%十六道智力锁%, 十六道智力锁解开就算过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    giveUp: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=1027.7"
  },
  {
    id: "g-164",
    season: 5,
    levelName: "小球回家",
    rule: "站在吧台一边往另一个方向丢乒乓球, 每次%同时丢出两颗乒乓球%, 且两颗乒乓球%同时落入纸杯中%。有乒乓球的纸杯%不能再丢%。每人都要进%两颗乒乓球%。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=1708.7"
  },
  {
    id: "g-165",
    season: 5,
    levelName: "猜号码",
    rule: "击打台球入袋后, 让女神猜台球号码, 猜错则要继续打。已经入袋台球%不能取出重复%。清台后%重新摆台继续%。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=1884.9"
  },
  {
    id: "g-166",
    season: 5,
    levelName: "挂衣架",
    rule: "站在%指定地点%投掷衣架, 将衣架挂在杆子上。每人%投中一个%就算过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=1972.1"
  },
  {
    id: "g-167",
    season: 5,
    levelName: "三渡扔瓶",
    rule: "在水池中划船%三个来回%, 每划一次可以扔一次水瓶。两人中有一人扔出水瓶%立在地面%就算过关。否则需要%重新划船%。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=2199.9"
  },
  {
    id: "g-168",
    season: 5,
    levelName: "赌徒游戏",
    rule: "进入此关每队固定罚时%三十分钟%, 需通过掷骰子%缩短或增加时长%。等待指定时间结束便可前往下一关。(%123增加五分钟, 456缩短五分钟%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 自来卷三木",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=2431.5"
  },
  {
    id: "g-169",
    season: 5,
    levelName: "射日游戏",
    rule: "每人都需要%射中十环%, 两人都命中就算过关。(%十环指黄色区域内位置%)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    giveUp: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=2792.2"
  },
  {
    id: "g-170",
    season: 5,
    levelName: "一筐乒乓",
    rule: "在%指定位置%投掷乒乓球, 装满%一筐%就算过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1z9bLzYEiC?t=3102.6"
  },
  {
    id: "g-171",
    season: 5,
    levelName: "扑克花色猜猜猜猜",
    rule: "只要%连续猜中%扑克牌花色%4次%即为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=258.1"
  },
  {
    id: "g-172",
    season: 5,
    levelName: "投币！！",
    rule: "把手中的硬币投入装满水的盆里, 只要水中的盘子内一次进入%>=5枚数量的硬币%则为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=469.5"
  },
  {
    id: "g-173",
    season: 5,
    levelName: "投壶2.0",
    rule: "两人%连续投壶3次%即为过关。(%不需要同时%)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=617.9"
  },
  {
    id: "g-174",
    season: 5,
    levelName: "地狱问答",
    rule: "%连续答对4道不同的问题%即为过关, 失败则会%回到上一关卡%。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "啊吗粽, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=1040.6"
  },
  {
    id: "g-175",
    season: 5,
    levelName: "羽毛球接接接",
    rule: "两人互相打羽毛球, 在%保证球不落地%的情况下, 从第1个球记起两人各接到%10次%即为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    giveUp: "雨哥到处跑, 自来卷三木, 啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=1425.9"
  },
  {
    id: "g-176",
    season: 5,
    levelName: "啊吗粽沙包(amzSB)",
    rule: "两人站在%规定距离外投沙包%, 得分%>=20%即为过关, 往后如有其他队%超过该分数%则需再回到此关继续投掷。(%禁止刷分%)",
    levelChampion: "啊吗粽, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=1964.8",
    isSpecialLevel: true,
    specialLevelType: 'sandbag',
    specialBestScore: '60分'
  },
  {
    id: "g-177",
    season: 5,
    levelName: "蒙眼金鸡独立",
    rule: "玩家需要抬起一只脚并且%超过膝盖%, 同时需要在%不睁开眼%的情况下独脚站立%一分钟%即为过关。(%不需要同时%)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=2132.7",
  },
  {
    id: "g-178",
    season: 5,
    levelName: "反应测测测",
    rule: "玩家需要在%屏幕变绿后点击屏幕%, 这个中间所用的时间%低于150ms%就算过关。(%提前点击则需要罚时一分钟%)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 力元君",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=2346.9",
  },
  {
    id: "g-179",
    season: 5,
    levelName: "扑克飞飞飞",
    rule: "任意一位玩家通过甩手中的扑克牌, %打破远处的水气球%即为过关。",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    giveUp: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=3097.7",
  },  
  {
    id: "g-180",
    season: 5,
    levelName: "把毽子踢进队友漏网里",
    rule: "双方分别%毽子踢到队友头顶的漏网中%即为过关。(%不用同时%)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=3708.3",
  },
  {
    id: "g-181",
    season: 5,
    levelName: "网球直投手",
    rule: "两位玩家分别把网球投入%不同观点洞内%即为过关。(%不能弹入%)",
    levelChampion: "雨哥到处跑, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=4005.7",
  },
  {
    id: "g-182",
    season: 5,
    levelName: "决战——乒乓争夺战",
    rule: "两队争夺水面的乒乓球并投入岸上的盆里, 规定%3分钟内%谁盆里的乒乓球%最多%谁就是冠军！！",
    levelChampion: "雨哥到处跑, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1S4YQzaEkj?t=4188.0",
  },
  {
    id: "g-183",
    season: 6,
    levelName: "谁是小丑王",
    rule: "两位玩家向空中%轮流抛出%手中的3颗球，抛出并接到算一分，两位玩家历史最高分数%相加>=20分%则为过关。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=260.5",
  },
  {
    id: "g-184",
    season: 6,
    levelName: "诗词作作作",
    rule: "两位玩家合力作出一首%七言绝句%就算过关。(通过与否由%女神决定%)",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=706.3",
  },
  {
    id: "g-185",
    season: 6,
    levelName: "捆绑回旋镖",
    rule: "两位玩家被%捆在一起%的同时，需要轮流向外投掷回旋镖，只要在回旋镖回来的途中%接到它%即为过关。(两人都需接到一次)",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=1185.7",
  },
  {
    id: "g-186",
    season: 6,
    levelName: "无畏契约定制关卡",
    rule: "玩家需要通过%抽签%完成每位游戏角色所代表的%游戏考验%。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=1958.9",
  },
  {
    id: "g-187",
    season: 6,
    levelName: "好色之图",
    rule: "找出每张图中%不同的色块%, 两位玩家历史最高得分%>=60%即为过关。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=2393.0",
  },
  {
    id: "g-188",
    season: 6,
    levelName: "国旗猜猜猜",
    rule: "两位玩家一起%连续猜中4个%国家的国旗就算过关。(不需要轮流猜)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    giveUp: "啊吗粽, 自来卷三木, 徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=2868.5",
  },
  {
    id: "g-189",
    season: 6,
    levelName: "逐步飞盘",
    rule: "两位玩家站在指定位置扔飞盘%穿过数字%，%轮流%从数字1飞到数字9即为过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV12zmGBcEtT?t=3436.5",
  },
  {
    id: "g-190",
    season: 6,
    levelName: "纸杯叠叠叠",
    rule: "两位玩家需要完成%叠收纸杯%这一动作，两人用时相加在%7秒以内%就算过关。(只记录历史好成绩)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=233.9",
  },
  {
    id: "g-191",
    season: 6,
    levelName: "火星撞地球",
    rule: "玩家需要在指定的距离击打白球, 使%乒乓球入洞%而%白球不入%即为过关。(每组一位过关即可)",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=500.9",
  },
  {
    id: "g-192",
    season: 6,
    levelName: "定点弹球",
    rule: "玩家需要使用网球通过地面%反弹进指定的桶内%即为过关。(两位玩家都要进球一次)",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=746.4",
  },
  {
    id: "g-193",
    season: 6,
    levelName: "新年快乐！(无畏契约赞助)",
    rule: "玩家需要在《无畏契约》游戏内使用枪械%摆“2026”字样%, 并祝贺屏幕前的观众朋友们%新年快乐%即可过关。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=991.5",
  },
  {
    id: "g-194",
    season: 6,
    levelName: "超绝炼狱深渊级终极骸栗惊悚蚂蚁搬糖",
    rule: "玩家需要找到蚂蚁且使蚂蚁把糖%搬离原地1cm%即可过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    giveUp: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=1316.9",
  },
  {
    id: "g-195",
    season: 6,
    levelName: "我测你的温...度",
    rule: "玩家需要使用测温枪在别墅内测出%女神指定的温度%即可过关。(误差为±0.5)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=1952.4",
  },
  {
    id: "g-196",
    season: 6,
    levelName: "指定跳远",
    rule: "两位玩家只要准确的跳到%女神给出的距离%即可过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=2288.3",
  },
  {
    id: "g-197",
    season: 6,
    levelName: "逐阶套圈",
    rule: "玩家需要由近到远%逐一圈中3个%雪糕桶即可过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1nKBXBCEoP?t=2570.2",
  },
  {
    id: "g-198",
    season: 6,
    levelName: "默契大挑战",
    rule: "两位玩家需要在一回合%同时吃到一样的食物%才算过关。(玩家之间不能说话)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=245.9",
  },
  {
    id: "g-199",
    season: 6,
    levelName: "叠杯子",
    rule: "两位玩家都需要叠到%与自己身高一样高%的杯子才算过关。(需同时过关)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=574.4",
  },
  {
    id: "g-200",
    season: 6,
    levelName: "海底捞球",
    rule: "两人需要在%10秒内%总共夹出%12颗乒乓球%才算过关。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    giveUp: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=1103.1",
  },
  {
    id: "g-201",
    season: 6,
    levelName: "圈地踏步",
    rule: "队伍两人皆需在圆圈内原地踏步%60秒%，且%结束后还在圈内%则过关。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=1557.7",
  },
  {
    id: "g-202",
    season: 6,
    levelName: "充电摇摇摇",
    rule: "使用手摇发电机使相机充到%3格电%即为过关。(3%的电)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=1952.9",
  },
  {
    id: "g-203",
    season: 6,
    levelName: "谁是人脉王",
    rule: "每人发一条朋友圈，两人%点赞人数%总共%达到100%即为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=2192.6",
  },
  {
    id: "g-204",
    season: 6,
    levelName: "空瓶捞捞捞",
    rule: "每人用绳圈套起地上的瓶子并使它%保持站立%即可过关。(手只能触碰绳子的末端)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=2491.5",
  },
  {
    id: "g-205",
    season: 6,
    levelName: "猜猜我是谁",
    rule: "每人发给裁判一张小时候的照片, 玩家需要依次猜出谁是谁, %全部答对%即为过关。(失败则罚时10分钟)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=2660.9",
  },
  {
    id: "g-206",
    season: 6,
    levelName: "红绿豆分分分",
    rule: "%分开碗中的红豆绿豆%即可过关。(方法不限)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "",
    url: "https://www.bilibili.com/video/BV1nDi9ByELu?t=2923.3",
  },
  {
    id: "g-207",
    season: 6,
    levelName: "甜蜜时刻",
    rule: "使用任何手段榨出一杯甘蔗汁并%喝掉%就算过关。(禁止使用榨汁机)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=452.1",
  },
  {
    id: "g-208",
    season: 6,
    levelName: "评分猜猜猜",
    rule: "%准确猜出%一部电影的评分即为过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=963.7",
  },
  {
    id: "g-209",
    season: 6,
    levelName: "彩票刮刮刮",
    rule: "每队%加时30分钟%, 刮中彩票减中奖相对应时间, 没中则每刮一张加5分钟。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=1245.9",
  },
  {
    id: "g-210",
    season: 6,
    levelName: "颜色猜猜猜",
    rule: "由女神调一个颜色, 队伍只要调出%跟女神一样的颜色%即可过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=1559.6",
  },
  {
    id: "g-211",
    season: 6,
    levelName: "AMZ沙包2.0",
    rule: "同组的两位玩家%连续投中洞内%即可过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    giveUp: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=2231.4",
  },
  {
    id: "g-212",
    season: 6,
    levelName: "靶场争锋(无畏契约赞助)",
    rule: "在鼠标速度不熟的情况在无畏契约最高难度靶场, %总计得分15%即可过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=2775.2",
  },
  {
    id: "g-213",
    season: 6,
    levelName: "噗桶发",
    rule: "两人普通话得分%≥90分%即为过关。(两人交替说词)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=3098.7",
  },
  {
    id: "g-214",
    season: 6,
    levelName: "竹蜻蜓",
    rule: "使用竹蜻蜓在规定位置%飞入桶内%即为过关。(单人即可)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "",
    url: "https://www.bilibili.com/video/BV1tKzcB1ECE?t=3516.8",
  },
  {
    id: "g-215",
    season: 6,
    levelName: "平衡杆",
    rule: "玩家需要一只手轮流去握两根杆子, %达到5次%即为过关。(需要双人过关)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=327.8",
  },
  {
    id: "g-216",
    season: 6,
    levelName: "蒙眼敲锣2.0",
    rule: "玩家需要在指定位置原地转3圈, 并且%敲到锣%才算过关。(单人过关)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=480.4",
  },
  {
    id: "g-217",
    season: 6,
    levelName: "按按按按按",
    rule: "玩家需要使用计算器一直+1+1+1+1+1+1...%10秒内按到100%即为过关。(单人过关即可)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=1263.9",
  },
  {
    id: "g-218",
    season: 6,
    levelName: "P图PPP",
    rule: "玩家需要把自己的照片P成抽到的其他玩家的样貌，且%女神猜出你P的是谁%就算过关。(双人过关)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=1771.1",
  },
  {
    id: "g-219",
    season: 6,
    levelName: "叠石头挑战",
    rule: "玩家需要把准备好的小石头%堆成指定长度%即为过关。(底部只能为一块石头)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    giveUp: "啊吗粽, 自来卷三木, 徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=2090.9",
  },
  {
    id: "g-220",
    season: 6,
    levelName: "古字猜猜猜",
    rule: "玩家需要%猜出随机到的6个%小篆体的简体字才算过关。(答错则需要5分钟后再答题)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    giveUp: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=2730.2",
  },
  {
    id: "g-221",
    season: 6,
    levelName: "纸飞机对撞挑战",
    rule: "两位玩家在规定距离间互相投纸飞机, 直到%两只飞机撞在一起%即为过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=3499.6",
  },
  {
    id: "g-222",
    season: 6,
    levelName: "奏乐猜歌",
    rule: "每位玩家需要从6件乐器中盲选一件并演奏一段, %女神猜出%即为过关。(每件乐器有相对应的说明书可以使用)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "徐大虾咯, 在下哲别",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=3883.4",
  },
  {
    id: "g-223",
    season: 6,
    levelName: "扎飞镖",
    rule: "玩家只需把飞镖%扎进女神扎过的格子%里就算过关。(双人过关)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "",
    url: "https://www.bilibili.com/video/BV1QfcVzVEwJ?t=4403.0",
  },
  {
    id: "g-224",
    season: 6,
    levelName: "听铃辨数",
    rule: "玩家在不观察铃铛, 且只能用耳朵听的情况下%辨别铃铛的数量%即可过关。",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=393.6",
  },
  {
    id: "g-225",
    season: 6,
    levelName: "接力保龄球",
    rule: "两人一人一球一回合内%击倒全部%保龄球瓶即为过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=443.1",
  },
  {
    id: "g-226",
    season: 6,
    levelName: "邦邦邦邦(无畏契约赞助)",
    rule: "使用5个飞刀%飞倒远处%的3只无畏契约玩偶即为过关。(一人过关即可)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=768.6",
  },
  {
    id: "g-227",
    season: 6,
    levelName: "画！",
    rule: "玩家需要以眼前的景象创作一幅画，%女神满意%即为过关。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=984.2",
  },
  {
    id: "g-228",
    season: 6,
    levelName: "音准测测测",
    rule: "由女神出题唱出一段声音, 玩家则需要%复刻同样的音准%并坚持到规定时长。",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=1416.2",
  },
  {
    id: "g-229",
    season: 6,
    levelName: "空中接力篮球",
    rule: "两人轮流抛起篮球, 抛起时需要双脚离地直到%每人抛起5次并投进篮筐%即为过关。(单人过关)",
    levelChampion: "雨哥到处跑, 力元君",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=1795.1",
  },
  {
    id: "g-230",
    season: 6,
    levelName: "再战心魔",
    rule: "使用升级后的卡片%飞爆指定距离外%的气球即为过关。(单人过关)",
    levelChampion: "啊吗粽, 自来卷三木",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "徐大虾咯, 在下哲别",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=2098.6",
  },
  {
    id: "g-231",
    season: 6,
    levelName: "省份猜猜猜",
    rule: "玩家需要连续且轮流的答出%6个地级市的省份%即为过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "雨哥到处跑, 力元君",
    levelThirdPlace: "啊吗粽, 自来卷三木",
    giveUp: "徐大虾咯, 在下哲别, 啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=2585.5",
  },
  {
    id: "g-232",
    season: 6,
    levelName: "π",
    rule: "玩家需要合作背出圆周率%后100位%才算过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "雨哥到处跑, 力元君",
    giveUp: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=3507.5",
  },
  {
    id: "g-233",
    season: 6,
    levelName: "影子猜猜猜",
    rule: "玩家只要猜出另一位玩家投射于墙上%影子的动物名称%即为过关。(由女神出题)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "雨哥到处跑, 力元君",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=4555.3",
  },
  {
    id: "g-234",
    season: 6,
    levelName: "冠军之路",
    rule: "玩家需要在这张极难的迷宫地图中找到一条%通往出口的路%才算过关。(单人过关)",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=4672.7",
  },
  {
    id: "g-235",
    season: 6,
    levelName: "决战门票-仰卧气球",
    rule: "玩家需要通过做仰卧起坐为气球充气直到%气球爆炸%才算过关。",
    levelChampion: "徐大虾咯, 在下哲别",
    levelRunnerUp: "啊吗粽, 自来卷三木",
    levelThirdPlace: "",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=4965.0",
  },
  {
    id: "f-006",
    season: 6,
    levelName: "S6决战",
    rule: "两队玩家要在%3分钟内收集%地上的乒乓球(1分)与网球(5分), 在指定位置投掷弹药进桶, %得分最多%队伍为总冠军。",
    levelChampion: "啊吗粽, 自来卷三木",
    url: "https://www.bilibili.com/video/BV11bAUzBEqG?t=5210.5",
  },
  // Additional games can be appended here statically as needed.
];
